version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15
    container_name: company_ai_postgres
    environment:
      POSTGRES_DB: company_ai
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

